theme = "my"

[keys.normal]
"ret" = "insert_mode"
"backspace" = "undo"
"z" = ":write"
"i" = "no_op"
"u" = "no_op"

"W" = "extend_next_word_start"
"space" = "keep_primary_selection"

"S-left" = "extend_char_left"
"S-right" = "extend_char_right"
"S-up" = "extend_visual_line_up"
"S-down" = "extend_visual_line_down"

[keys.normal.","]
"f" = "file_picker"
"F" = "file_picker_in_current_directory"
"b" = "buffer_picker"
"j" = "jumplist_picker"
"g" = "changed_file_picker"
"k" = "hover"
"d" = "diagnostics_picker"
"D" = "workspace_diagnostics_picker"
"r" = "rename_symbol"
"a" = "code_action"
"h" = "select_references_to_symbol_under_cursor"
"'" = "last_picker"
"c" = "toggle_comments"
"p" = "paste_clipboard_after"
"P" = "paste_clipboard_before"
"y" = "yank_to_clipboard"
"Y" = "yank_main_selection_to_clipboard"
"R" = "replace_selections_with_clipboard"
"/" = "global_search"
"?" = "command_palette"

[keys.normal."G"]
"e" = "extend_to_last_line"
