[misc]
assume_yes = true
no_retry = true
cleanup = true
skip_notify = true
no_self_update = true
disable = [
    "containers",
    "github_cli_extensions",
    "git_repos",
    "hyprpm",
    "kakoune",
]

[commands]
"Dipm" = "dipm update"
